### ISSUE TITLE
Add new words

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#273] opened 2015-01-28 02:39 UTC
1. @mmcauliffe  mentioned in the meeting on Tuesday that AutoSave will not save words that are added to the corpus, but this seems to be false. (That's fine, but I thought you should know!) If auto-save is off, it does correctly prompt for saving, but if auto-save is on, there is no prompt, but the new word is also there on re-load.

2. In creating a subset of the example corpus (which doesn't carry the feature system with it -- I assume that will be fixed with the other feature errors related to the example corpora?), and then trying to add a new word to the subset corpus, it seems to work, but every time I enter a click on a segment to add to the transcription, the following error is generated:

![error_in_adding_transcription_of_new_word](https://cloud.githubusercontent.com/assets/7317450/5931502/9024be98-a653-11e4-9d12-9627bef1ccc0.jpg)

**Comment by mmcauliffe** [comment] 2015-01-28 23:27
Could you test this one again for me?  It should be resolved, but I think it's caused by old example corpus, but it should work.

Yeah, the general rule that I was following with autosaving was that any additions would be autosaved, any changes or removals would not be autosaved, so that fits in with that.  Sorry about the confusion!

**Comment by mmcauliffe** [comment] 2015-02-02 01:08
I'm gonna close this!

**Closed by mmcauliffe** 2015-02-02 01:08 UTC
Labels: bug
